spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=RentalSystemDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=tom
spring.datasource.password=654832
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 可選：先讓 Hibernate 不要亂建表（你們資料表已存在通常用 validate）
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8081

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
