server:
  port: 8080

app:
  file:
    upload-path: uploads

spring:
  profiles:
    active: local

  application:
    name: seat-rent-backend

  # --- 新增 Google OAuth2 設定 ---
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 231325237264-ngpc81gmkl8pop0nq8jlgv0g63pj9fjg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.default_schema]": dbo
      "[hibernate.dialect]": org.hibernate.dialect.SQLServerDialect
      "[hibernate.jdbc.lob.non_contextual_creation]": true

  # --- 新增郵件發送設定 ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: alan123149@gmail.com
    password: nyjctvblehdjzxbc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
